apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${{ values.component_id }}-project
  namespace: argocd
spec:
  description: Project for ${{ values.component_id }}
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'