apiVersion: v1
kind: Service
metadata:
  name: ${{ values.component_id }}
spec:
  selector:
    app: ${{ values.component_id }}
  ports:
  - name: web
    nodePort: 30084
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
